"""add tmall ijcai 2015 schema

Revision ID: bea2b5793f31
Revises: 20260924ba02
Create Date: 2026-09-25 14:35:21.478587

新增天猫 IJCAI 2015 数据集的 Silver / Gold 共 10 张表。

**这张迁移只建结构，不导入任何数据。** 数据由
`backend/scripts/ingest_tmall_data.py` 单独执行，因为导入要读 1.9GB 的 ZIP、
要跑几分钟，把它塞进迁移会让 `alembic upgrade head` 变得不可预期。
结构变更与数据装载分开，也是「迁移可重复、数据可重导」的前提。

本文件由 autogenerate 生成后**手工删掉了与天猫无关的部分**：
`business_analysis_*` 与 `checkpoint*` / `store*` 系列表在数据库里存在，
但没有登记进 `app.models.Base.metadata`（它们由各自模块自行建表），
autogenerate 因此把它们误判成「已删除」。直接采纳那份输出会**删掉生产数据**。
这属于已知的既有漂移，不在本次改动范围内，所以这里只保留天猫的建表语句。

三个设计决定值得写下来：

1. **tmall_ingestion_runs 不加唯一约束。**
   它是运行台账，同一份文件失败两次、重试三次都应该各留一条记录。
   幂等判定靠查询 `status = 'succeeded'`，不靠约束。
   判定的四列建了联合索引 `ix_tmall_ingestion_runs_identity`。

2. **tmall_user_events.source_row_number 唯一。**
   它是「原始文件里的数据行序号」，重复导入同一份文件时必然冲突——
   让数据库在写入那一刻就拒绝，比在应用层比对行数更可靠。

3. **tmall_repurchase_samples 有 label / split 归属约束。**
   train 行必须有 label 且不能有 probability；test 行不能有 label，
   probability 可以为空——官方发布的 `test_format1.csv` 里 prob 列
   是整列为空的（它留给参赛者写预测结果）。不加约束的话，
   把 prob 错写进 label 是一个**静默**错误：按 label 算的正样本率
   看起来完全合理，但数字是错的。

4. **tmall_merchant_metrics 的 repeat_buy_user_count 带一条「不超过
   buy_user_count」的约束。** 「买过 ≥2 次」是「买过 ≥1 次」的子集，
   所以这条约束在正确实现下恒成立；它的价值是在刷新 SQL 写错聚合口径时
   当场拒绝，而不是把一个大于分母的比率写进 Gold 表。

   同一批改动还修正了 `repeat_buy_flag` 的口径：它原本表示
   「在 ≥2 个**不同商家**买过」，那是购买广度而不是复购。现在它表示
   「在同一个商家买过 ≥2 次」，广度改由 `multi_merchant_buy_flag` 表达。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea2b5793f31'
down_revision: Union[str, Sequence[str], None] = '20260924ba02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmall_category_metrics',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('user_count', sa.BigInteger(), nullable=False),
    sa.Column('item_count', sa.BigInteger(), nullable=False),
    sa.Column('merchant_count', sa.BigInteger(), nullable=False),
    sa.Column('click_count', sa.BigInteger(), nullable=False),
    sa.Column('cart_count', sa.BigInteger(), nullable=False),
    sa.Column('favorite_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_user_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_user_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('event_count >= 0', name=op.f('ck_tmall_category_metrics_event_count_not_negative')),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_tmall_category_metrics')),
    comment='Gold：按类目（原 cat_id）的行为汇总'
    )
    op.create_table('tmall_daily_metrics',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('user_count', sa.BigInteger(), nullable=False),
    sa.Column('item_count', sa.BigInteger(), nullable=False),
    sa.Column('merchant_count', sa.BigInteger(), nullable=False),
    sa.Column('category_count', sa.BigInteger(), nullable=False),
    sa.Column('event_share', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('user_share', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint("action_type IN ('click', 'cart', 'favorite', 'buy')", name=op.f('ck_tmall_daily_metrics_action_type')),
    sa.PrimaryKeyConstraint('metric_date', 'action_type', name=op.f('pk_tmall_daily_metrics')),
    comment='Gold：按天 × 动作的用户数与事件数'
    )
    op.create_table('tmall_funnel_metrics',
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('user_count', sa.BigInteger(), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('user_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('event_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint("action_type IN ('click', 'cart', 'favorite', 'buy')", name=op.f('ck_tmall_funnel_metrics_action_type')),
    sa.CheckConstraint('step_order BETWEEN 1 AND 4', name=op.f('ck_tmall_funnel_metrics_step_order_range')),
    sa.PrimaryKeyConstraint('action_type', name=op.f('pk_tmall_funnel_metrics')),
    comment='Gold：全局行为漏斗（用户级去重，非 session 顺序漏斗）'
    )
    op.create_table('tmall_ingestion_runs',
    sa.Column('run_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sample_modulus', sa.Integer(), nullable=False),
    sa.Column('sample_residue', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_row_count', sa.BigInteger(), nullable=True),
    sa.Column('imported_row_count', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f('ck_tmall_ingestion_runs_status')),
    sa.CheckConstraint('sample_modulus > 0', name=op.f('ck_tmall_ingestion_runs_sample_modulus_positive')),
    sa.CheckConstraint('sample_residue >= 0 AND sample_residue < sample_modulus', name=op.f('ck_tmall_ingestion_runs_sample_residue_range')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_tmall_ingestion_runs')),
    comment='天猫数据导入运行台账：文件指纹、抽样参数、状态与计数'
    )
    op.create_index('ix_tmall_ingestion_runs_identity', 'tmall_ingestion_runs', ['sha256', 'sample_modulus', 'sample_residue', 'status'], unique=False)
    op.create_table('tmall_merchant_metrics',
    sa.Column('merchant_id', sa.BigInteger(), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('user_count', sa.BigInteger(), nullable=False),
    sa.Column('item_count', sa.BigInteger(), nullable=False),
    sa.Column('category_count', sa.BigInteger(), nullable=False),
    sa.Column('click_count', sa.BigInteger(), nullable=False),
    sa.Column('cart_count', sa.BigInteger(), nullable=False),
    sa.Column('favorite_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_user_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_user_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('repeat_buy_user_count', sa.BigInteger(), nullable=False),
    sa.Column('repeat_buy_user_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('event_count >= 0', name=op.f('ck_tmall_merchant_metrics_event_count_not_negative')),
    sa.CheckConstraint('repeat_buy_user_count >= 0 AND repeat_buy_user_count <= buy_user_count', name=op.f('ck_tmall_merchant_metrics_repeat_buy_user_count_within_buy_users')),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_tmall_merchant_metrics')),
    comment='Gold：按商家（原 seller_id）的行为汇总'
    )
    op.create_table('tmall_repurchase_metrics',
    sa.Column('dataset_split', sa.String(length=8), nullable=False),
    sa.Column('label_group', sa.String(length=16), nullable=False),
    sa.Column('sample_count', sa.BigInteger(), nullable=False),
    sa.Column('user_count', sa.BigInteger(), nullable=False),
    sa.Column('merchant_count', sa.BigInteger(), nullable=False),
    sa.Column('positive_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('average_probability', sa.Numeric(precision=8, scale=7), nullable=True),
    sa.CheckConstraint("dataset_split IN ('train', 'test')", name=op.f('ck_tmall_repurchase_metrics_dataset_split')),
    sa.CheckConstraint("label_group IN ('positive', 'negative', 'unlabeled')", name=op.f('ck_tmall_repurchase_metrics_label_group')),
    sa.PrimaryKeyConstraint('dataset_split', 'label_group', name=op.f('pk_tmall_repurchase_metrics')),
    comment='Gold：复购样本的标签分布与平均预测概率'
    )
    op.create_table('tmall_repurchase_samples',
    sa.Column('sample_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_split', sa.String(length=8), nullable=False),
    sa.Column('label', sa.SmallInteger(), nullable=True),
    sa.Column('probability', sa.Numeric(precision=8, scale=7), nullable=True),
    sa.CheckConstraint("(dataset_split = 'train' AND label IS NOT NULL AND probability IS NULL) OR (dataset_split = 'test' AND label IS NULL)", name=op.f('ck_tmall_repurchase_samples_label_split_exclusive')),
    sa.CheckConstraint("dataset_split IN ('train', 'test')", name=op.f('ck_tmall_repurchase_samples_dataset_split')),
    sa.CheckConstraint('label IS NULL OR label IN (0, 1)', name=op.f('ck_tmall_repurchase_samples_label_binary')),
    sa.CheckConstraint('probability IS NULL OR (probability >= 0 AND probability <= 1)', name=op.f('ck_tmall_repurchase_samples_probability_unit_interval')),
    sa.PrimaryKeyConstraint('sample_id', name=op.f('pk_tmall_repurchase_samples')),
    sa.UniqueConstraint('user_id', 'merchant_id', 'dataset_split', name=op.f('uq_tmall_repurchase_samples_user_id_merchant_id_dataset_split')),
    comment='天猫复购预测样本：train 有 label，test 的 probability 可为空'
    )
    op.create_index(op.f('ix_tmall_repurchase_samples_dataset_split'), 'tmall_repurchase_samples', ['dataset_split'], unique=False)
    op.create_index(op.f('ix_tmall_repurchase_samples_merchant_id'), 'tmall_repurchase_samples', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_tmall_repurchase_samples_user_id'), 'tmall_repurchase_samples', ['user_id'], unique=False)
    op.create_table('tmall_user_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_row_number', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.CheckConstraint("action_type IN ('click', 'cart', 'favorite', 'buy')", name=op.f('ck_tmall_user_events_action_type')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_tmall_user_events')),
    comment='天猫用户行为日志明细：click / cart / favorite / buy'
    )
    op.create_index(op.f('ix_tmall_user_events_action_type'), 'tmall_user_events', ['action_type'], unique=False)
    op.create_index(op.f('ix_tmall_user_events_brand_id'), 'tmall_user_events', ['brand_id'], unique=False)
    op.create_index(op.f('ix_tmall_user_events_category_id'), 'tmall_user_events', ['category_id'], unique=False)
    op.create_index(op.f('ix_tmall_user_events_event_date'), 'tmall_user_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_tmall_user_events_item_id'), 'tmall_user_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_tmall_user_events_merchant_id'), 'tmall_user_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_tmall_user_events_source_row_number'), 'tmall_user_events', ['source_row_number'], unique=True)
    op.create_index(op.f('ix_tmall_user_events_user_id'), 'tmall_user_events', ['user_id'], unique=False)
    op.create_table('tmall_user_metrics',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('item_count', sa.BigInteger(), nullable=False),
    sa.Column('merchant_count', sa.BigInteger(), nullable=False),
    sa.Column('category_count', sa.BigInteger(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.BigInteger(), nullable=False),
    sa.Column('cart_count', sa.BigInteger(), nullable=False),
    sa.Column('favorite_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_count', sa.BigInteger(), nullable=False),
    sa.Column('buy_merchant_count', sa.BigInteger(), nullable=False),
    sa.Column('multi_merchant_buy_flag', sa.Boolean(), nullable=False),
    sa.Column('repeat_buy_flag', sa.Boolean(), nullable=False),
    sa.Column('first_event_date', sa.Date(), nullable=False),
    sa.Column('last_event_date', sa.Date(), nullable=False),
    sa.CheckConstraint('event_count >= 0', name=op.f('ck_tmall_user_metrics_event_count_not_negative')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_tmall_user_metrics')),
    comment='Gold：按用户的行为汇总'
    )
    op.create_table('tmall_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age_range', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('age_range IS NULL OR age_range >= 0', name=op.f('ck_tmall_users_age_range_not_negative')),
    sa.CheckConstraint('gender IS NULL OR gender >= 0', name=op.f('ck_tmall_users_gender_not_negative')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_tmall_users')),
    comment='天猫用户画像：age_range / gender 编码含义见知识库数据字典'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmall_users')
    op.drop_table('tmall_user_metrics')
    op.drop_index(op.f('ix_tmall_user_events_user_id'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_source_row_number'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_merchant_id'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_item_id'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_event_date'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_category_id'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_brand_id'), table_name='tmall_user_events')
    op.drop_index(op.f('ix_tmall_user_events_action_type'), table_name='tmall_user_events')
    op.drop_table('tmall_user_events')
    op.drop_index(op.f('ix_tmall_repurchase_samples_user_id'), table_name='tmall_repurchase_samples')
    op.drop_index(op.f('ix_tmall_repurchase_samples_merchant_id'), table_name='tmall_repurchase_samples')
    op.drop_index(op.f('ix_tmall_repurchase_samples_dataset_split'), table_name='tmall_repurchase_samples')
    op.drop_table('tmall_repurchase_samples')
    op.drop_table('tmall_repurchase_metrics')
    op.drop_table('tmall_merchant_metrics')
    op.drop_index('ix_tmall_ingestion_runs_identity', table_name='tmall_ingestion_runs')
    op.drop_table('tmall_ingestion_runs')
    op.drop_table('tmall_funnel_metrics')
    op.drop_table('tmall_daily_metrics')
    op.drop_table('tmall_category_metrics')
    # ### end Alembic commands ###
