"""create retail analytics schema

Revision ID: e205344666e8
Revises: 
Create Date: 2026-09-22 21:36:29.802891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e205344666e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=12), nullable=False),
    sa.Column('customer_name', sa.String(length=64), nullable=False),
    sa.Column('member_level', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("member_level IN ('普通会员', '银卡会员', '金卡会员', '黑金会员')", name=op.f('ck_customers_member_level')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    comment='客户维度表：会员等级用于复购率分析'
    )
    op.create_index(op.f('ix_customers_member_level'), 'customers', ['member_level'], unique=False)
    op.create_table('date_dim',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('month_name', sa.String(length=16), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('week_of_year', sa.SmallInteger(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_date_dim_month_range')),
    sa.CheckConstraint('quarter BETWEEN 1 AND 4', name=op.f('ck_date_dim_quarter_range')),
    sa.PrimaryKeyConstraint('date_id', name=op.f('pk_date_dim')),
    sa.UniqueConstraint('full_date', name=op.f('uq_date_dim_full_date')),
    comment='日期维度表：覆盖 2025 全年，订单按 date_id 关联'
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=False),
    sa.Column('category_name', sa.String(length=32), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unit_price > 0', name=op.f('ck_products_unit_price_positive')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products')),
    comment='商品维度表：category_name 用于品类销售分析'
    )
    op.create_index(op.f('ix_products_category_name'), 'products', ['category_name'], unique=False)
    op.create_table('regions',
    sa.Column('region_id', sa.String(length=8), nullable=False),
    sa.Column('region_name', sa.String(length=32), nullable=False),
    sa.Column('region_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk_regions')),
    sa.UniqueConstraint('region_name', name=op.f('uq_regions_region_name')),
    comment='区域维度表：region_name 唯一'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.String(length=12), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('region_id', sa.String(length=8), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('discount_amount <= gross_amount', name=op.f('ck_orders_discount_not_exceed_gross')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_orders_discount_amount_not_negative')),
    sa.CheckConstraint('gross_amount >= 0', name=op.f('ck_orders_gross_amount_not_negative')),
    sa.CheckConstraint('net_amount = gross_amount - discount_amount', name=op.f('ck_orders_net_amount_consistent')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_orders_unit_price_not_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_orders_customer_id')),
    sa.ForeignKeyConstraint(['date_id'], ['date_dim.date_id'], name=op.f('fk_orders_date_id')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_orders_product_id')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_orders_region_id')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders')),
    comment='订单事实表：gross=数量×单价，net=gross-折扣'
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_date_id'), 'orders', ['date_id'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_region_id'), 'orders', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_region_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_date_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('regions')
    op.drop_index(op.f('ix_products_category_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('date_dim')
    op.drop_index(op.f('ix_customers_member_level'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
